//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.7.2558.0.
// 
namespace SDKPaylineDotNet.MassPaymentAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MassPaymentAPISoapBinding", Namespace="http://impl.ws.payline.experian.com")]
    public partial class MassPaymentAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback doMassCaptureOperationCompleted;
        
        private System.Threading.SendOrPostCallback doMassRefundOperationCompleted;
        
        private System.Threading.SendOrPostCallback doMassResetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMassTraitmentDetailsOperationCompleted;
        
        /// <remarks/>
        public MassPaymentAPI() {
            this.Url = "http://host/V4/services/MassPaymentAPI";
        }
        
        /// <remarks/>
        public event doMassCaptureCompletedEventHandler doMassCaptureCompleted;
        
        /// <remarks/>
        public event doMassRefundCompletedEventHandler doMassRefundCompleted;
        
        /// <remarks/>
        public event doMassResetCompletedEventHandler doMassResetCompleted;
        
        /// <remarks/>
        public event getMassTraitmentDetailsCompletedEventHandler getMassTraitmentDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("doMassCapture", RequestElementName="doMassCaptureRequest", RequestNamespace="http://impl.ws.payline.experian.com", ResponseNamespace="http://impl.ws.payline.experian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public result doMassCapture(string version, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://obj.ws.payline.experian.com", IsNullable=false)] capture[] captureAuthorizationList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string comment, out string massTraitmentID, out string date) {
            object[] results = this.Invoke("doMassCapture", new object[] {
                        version,
                        captureAuthorizationList,
                        comment});
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindoMassCapture(string version, capture[] captureAuthorizationList, string comment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("doMassCapture", new object[] {
                        version,
                        captureAuthorizationList,
                        comment}, callback, asyncState);
        }
        
        /// <remarks/>
        public result EnddoMassCapture(System.IAsyncResult asyncResult, out string massTraitmentID, out string date) {
            object[] results = this.EndInvoke(asyncResult);
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public void doMassCaptureAsync(string version, capture[] captureAuthorizationList, string comment) {
            this.doMassCaptureAsync(version, captureAuthorizationList, comment, null);
        }
        
        /// <remarks/>
        public void doMassCaptureAsync(string version, capture[] captureAuthorizationList, string comment, object userState) {
            if ((this.doMassCaptureOperationCompleted == null)) {
                this.doMassCaptureOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoMassCaptureOperationCompleted);
            }
            this.InvokeAsync("doMassCapture", new object[] {
                        version,
                        captureAuthorizationList,
                        comment}, this.doMassCaptureOperationCompleted, userState);
        }
        
        private void OndoMassCaptureOperationCompleted(object arg) {
            if ((this.doMassCaptureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doMassCaptureCompleted(this, new doMassCaptureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("doMassRefund", RequestElementName="doMassRefundRequest", RequestNamespace="http://impl.ws.payline.experian.com", ResponseNamespace="http://impl.ws.payline.experian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public result doMassRefund(string version, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://obj.ws.payline.experian.com", IsNullable=false)] refund[] refundAuthorizationList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string comment, out string massTraitmentID, out string date) {
            object[] results = this.Invoke("doMassRefund", new object[] {
                        version,
                        refundAuthorizationList,
                        comment});
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindoMassRefund(string version, refund[] refundAuthorizationList, string comment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("doMassRefund", new object[] {
                        version,
                        refundAuthorizationList,
                        comment}, callback, asyncState);
        }
        
        /// <remarks/>
        public result EnddoMassRefund(System.IAsyncResult asyncResult, out string massTraitmentID, out string date) {
            object[] results = this.EndInvoke(asyncResult);
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public void doMassRefundAsync(string version, refund[] refundAuthorizationList, string comment) {
            this.doMassRefundAsync(version, refundAuthorizationList, comment, null);
        }
        
        /// <remarks/>
        public void doMassRefundAsync(string version, refund[] refundAuthorizationList, string comment, object userState) {
            if ((this.doMassRefundOperationCompleted == null)) {
                this.doMassRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoMassRefundOperationCompleted);
            }
            this.InvokeAsync("doMassRefund", new object[] {
                        version,
                        refundAuthorizationList,
                        comment}, this.doMassRefundOperationCompleted, userState);
        }
        
        private void OndoMassRefundOperationCompleted(object arg) {
            if ((this.doMassRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doMassRefundCompleted(this, new doMassRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("doMassReset", RequestElementName="doMassResetRequest", RequestNamespace="http://impl.ws.payline.experian.com", ResponseNamespace="http://impl.ws.payline.experian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public result doMassReset(string version, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("transactionID", Namespace="http://obj.ws.payline.experian.com", IsNullable=false)] string[] resetAuthorizationList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string comment, out string massTraitmentID, out string date) {
            object[] results = this.Invoke("doMassReset", new object[] {
                        version,
                        resetAuthorizationList,
                        comment});
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindoMassReset(string version, string[] resetAuthorizationList, string comment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("doMassReset", new object[] {
                        version,
                        resetAuthorizationList,
                        comment}, callback, asyncState);
        }
        
        /// <remarks/>
        public result EnddoMassReset(System.IAsyncResult asyncResult, out string massTraitmentID, out string date) {
            object[] results = this.EndInvoke(asyncResult);
            massTraitmentID = ((string)(results[1]));
            date = ((string)(results[2]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public void doMassResetAsync(string version, string[] resetAuthorizationList, string comment) {
            this.doMassResetAsync(version, resetAuthorizationList, comment, null);
        }
        
        /// <remarks/>
        public void doMassResetAsync(string version, string[] resetAuthorizationList, string comment, object userState) {
            if ((this.doMassResetOperationCompleted == null)) {
                this.doMassResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoMassResetOperationCompleted);
            }
            this.InvokeAsync("doMassReset", new object[] {
                        version,
                        resetAuthorizationList,
                        comment}, this.doMassResetOperationCompleted, userState);
        }
        
        private void OndoMassResetOperationCompleted(object arg) {
            if ((this.doMassResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doMassResetCompleted(this, new doMassResetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("getMassTraitmentDetails", RequestElementName="getMassTraitmentDetailsRequest", RequestNamespace="http://impl.ws.payline.experian.com", ResponseNamespace="http://impl.ws.payline.experian.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public result getMassTraitmentDetails(string version, string massTraitmentID, out string massTraitementID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string totalLinesNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] out string failedLinesNumber, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute("failedObject", Namespace="http://obj.ws.payline.experian.com", IsNullable=false)] out transaction[] failedListObject) {
            object[] results = this.Invoke("getMassTraitmentDetails", new object[] {
                        version,
                        massTraitmentID});
            massTraitementID = ((string)(results[1]));
            totalLinesNumber = ((string)(results[2]));
            failedLinesNumber = ((string)(results[3]));
            failedListObject = ((transaction[])(results[4]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetMassTraitmentDetails(string version, string massTraitmentID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getMassTraitmentDetails", new object[] {
                        version,
                        massTraitmentID}, callback, asyncState);
        }
        
        /// <remarks/>
        public result EndgetMassTraitmentDetails(System.IAsyncResult asyncResult, out string massTraitementID, out string totalLinesNumber, out string failedLinesNumber, out transaction[] failedListObject) {
            object[] results = this.EndInvoke(asyncResult);
            massTraitementID = ((string)(results[1]));
            totalLinesNumber = ((string)(results[2]));
            failedLinesNumber = ((string)(results[3]));
            failedListObject = ((transaction[])(results[4]));
            return ((result)(results[0]));
        }
        
        /// <remarks/>
        public void getMassTraitmentDetailsAsync(string version, string massTraitmentID) {
            this.getMassTraitmentDetailsAsync(version, massTraitmentID, null);
        }
        
        /// <remarks/>
        public void getMassTraitmentDetailsAsync(string version, string massTraitmentID, object userState) {
            if ((this.getMassTraitmentDetailsOperationCompleted == null)) {
                this.getMassTraitmentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMassTraitmentDetailsOperationCompleted);
            }
            this.InvokeAsync("getMassTraitmentDetails", new object[] {
                        version,
                        massTraitmentID}, this.getMassTraitmentDetailsOperationCompleted, userState);
        }
        
        private void OngetMassTraitmentDetailsOperationCompleted(object arg) {
            if ((this.getMassTraitmentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMassTraitmentDetailsCompleted(this, new getMassTraitmentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class capture {
        
        private string transactionIDField;
        
        private payment paymentField;
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public payment payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class payment {
        
        private string amountField;
        
        private string currencyField;
        
        private string actionField;
        
        private string modeField;
        
        private string contractNumberField;
        
        private string differedActionDateField;
        
        private string methodField;
        
        private string softDescriptorField;
        
        private string cardBrandField;
        
        private string registrationTokenField;
        
        private string cumulatedAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        public string contractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string differedActionDate {
            get {
                return this.differedActionDateField;
            }
            set {
                this.differedActionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string softDescriptor {
            get {
                return this.softDescriptorField;
            }
            set {
                this.softDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardBrand {
            get {
                return this.cardBrandField;
            }
            set {
                this.cardBrandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string registrationToken {
            get {
                return this.registrationTokenField;
            }
            set {
                this.registrationTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cumulatedAmount {
            get {
                return this.cumulatedAmountField;
            }
            set {
                this.cumulatedAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class avs {
        
        private string resultField;
        
        private string resultFromAcquirerField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string resultFromAcquirer {
            get {
                return this.resultFromAcquirerField;
            }
            set {
                this.resultFromAcquirerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class scoring {
        
        private string partnerIdField;
        
        private string orderIdField;
        
        private string valueField;
        
        private string responseField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string partnerId {
            get {
                return this.partnerIdField;
            }
            set {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class fraudResultDetails {
        
        private string codeField;
        
        private string shortMessageField;
        
        private string longMessageField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string shortMessage {
            get {
                return this.shortMessageField;
            }
            set {
                this.shortMessageField = value;
            }
        }
        
        /// <remarks/>
        public string longMessage {
            get {
                return this.longMessageField;
            }
            set {
                this.longMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class transaction {
        
        private string idField;
        
        private string dateField;
        
        private string isDuplicatedField;
        
        private string isPossibleFraudField;
        
        private string fraudResultField;
        
        private fraudResultDetails fraudResultDetailsField;
        
        private string explanationField;
        
        private string threeDSecureField;
        
        private string softDescriptorField;
        
        private string scoreField;
        
        private scoring scoringField;
        
        private string externalWalletTypeField;
        
        private string externalWalletContractNumberField;
        
        private string partnerAdditionalDataField;
        
        private avs avsField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isDuplicated {
            get {
                return this.isDuplicatedField;
            }
            set {
                this.isDuplicatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isPossibleFraud {
            get {
                return this.isPossibleFraudField;
            }
            set {
                this.isPossibleFraudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fraudResult {
            get {
                return this.fraudResultField;
            }
            set {
                this.fraudResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public fraudResultDetails fraudResultDetails {
            get {
                return this.fraudResultDetailsField;
            }
            set {
                this.fraudResultDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string explanation {
            get {
                return this.explanationField;
            }
            set {
                this.explanationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string threeDSecure {
            get {
                return this.threeDSecureField;
            }
            set {
                this.threeDSecureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string softDescriptor {
            get {
                return this.softDescriptorField;
            }
            set {
                this.softDescriptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public scoring scoring {
            get {
                return this.scoringField;
            }
            set {
                this.scoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string externalWalletType {
            get {
                return this.externalWalletTypeField;
            }
            set {
                this.externalWalletTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string externalWalletContractNumber {
            get {
                return this.externalWalletContractNumberField;
            }
            set {
                this.externalWalletContractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string partnerAdditionalData {
            get {
                return this.partnerAdditionalDataField;
            }
            set {
                this.partnerAdditionalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public avs avs {
            get {
                return this.avsField;
            }
            set {
                this.avsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class refund {
        
        private string transactionIDField;
        
        private payment paymentField;
        
        /// <remarks/>
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public payment payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://obj.ws.payline.experian.com")]
    public partial class result {
        
        private string codeField;
        
        private string shortMessageField;
        
        private string longMessageField;
        
        private string partnerCodeField;
        
        private string partnerCodeLabelField;
        
        /// <remarks/>
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string shortMessage {
            get {
                return this.shortMessageField;
            }
            set {
                this.shortMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string longMessage {
            get {
                return this.longMessageField;
            }
            set {
                this.longMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string partnerCode {
            get {
                return this.partnerCodeField;
            }
            set {
                this.partnerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string partnerCodeLabel {
            get {
                return this.partnerCodeLabelField;
            }
            set {
                this.partnerCodeLabelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void doMassCaptureCompletedEventHandler(object sender, doMassCaptureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doMassCaptureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doMassCaptureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((result)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string massTraitmentID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void doMassRefundCompletedEventHandler(object sender, doMassRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doMassRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doMassRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((result)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string massTraitmentID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void doMassResetCompletedEventHandler(object sender, doMassResetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doMassResetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doMassResetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((result)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string massTraitmentID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    public delegate void getMassTraitmentDetailsCompletedEventHandler(object sender, getMassTraitmentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMassTraitmentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMassTraitmentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((result)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string massTraitementID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string totalLinesNumber {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string failedLinesNumber {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public transaction[] failedListObject {
            get {
                this.RaiseExceptionIfNecessary();
                return ((transaction[])(this.results[4]));
            }
        }
    }
}
